linha_unica1 = input().split()
#print(linha_unica1)
p1 = int(linha_unica1[0])
n1 = int(linha_unica1[1])
v1 = float(linha_unica1[2])
linha_unica2 = input().split()
p2 = int(linha_unica2[0])
n2 = int(linha_unica2[1])
v2 = float(linha_unica2[2])
VALOR_TOTAL = (n1*v1) + (n2*v2)
print(f"VALOR A PAGAR: R$ {VALOR_TOTAL:.2f}")